spring:
  application:
    name: notification-service
  config:
    import: "optional:configserver:http://localhost:8088"
  cache:
    type: redis
    redis:
      cache-null-values: false
      use-key-prefix: true
      time-to-live: 3000
  data:
    redis:
      host: redis-14442.c1.ap-southeast-1-1.ec2.cloud.redislabs.com
      port: 14442
      username: default
      password: N7YhN4jXP6ASKBHRR9iLYJun9bXCRfAL
      havePassword: NO
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: chat_notify
#      username: admin
#      password: Son191203