server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:3000"
            allowed-headers:
              - "*"
            allowed-methods:
              - GET
              - POST
      routes:
        - id: cinema-service
          uri: lb://cinema-service
          predicates:
            - Path=/cinema/**
          filters:
            - AuthenticationFilter
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/booking/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification/**
          filters:
            - AuthenticationFilter
        - id: mail-service
          uri: lb://mail-service
          predicates:
            - Path=/mail/**
          filters:
            - AuthenticationFilter
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - AuthenticationFilter
        - id: movie-service
          uri: lb://movie-service
          predicates:
            - Path=/movie/**
          filters:
            - AuthenticationFilter