spring:
  application:
    name: cinema-service
  config:
    import: "optional:configserver:http://localhost:8088"
  datasource:
    url: jdbc:mysql://localhost:3306/cinema-service
    username: root
    password: Son191203
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
    cache:
      type: redis
      redis:
        cache-null-values: false
        use-key-prefix: true
        time-to-live: 3000
    data:
      redis:
        host: redis-14618.c292.ap-southeast-1-1.ec2.redns.redis-cloud.com
        port: 14618
        username: default
        password: bq2UkSMCAxrdm1aYvJnpkXGokVZNqapK
        havePassword: YES
