spring:
  application:
    name: core
  cache:
    type: redis
    redis:
      cache-null-values: false
      use-key-prefix: true
      time-to-live: 3000
  data:
    redis:
      host: redis-14442.c1.ap-southeast-1-1.ec2.cloud.redislabs.com
      port: 14442
      username: default
      password: N7YhN4jXP6ASKBHRR9iLYJun9bXCRfAL
  security:
    jwt:
      secret_key: eyJhbGciOiJIUzUxMiJ9eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTcwMTA1NjM3OSwiaWF0IjoxNzAx
      expiration_time: 5
cloudiary:
  cloud_name: dm256lpnu
  api_key: 463632651578279
  api_secret: CEQdGRFAMKw29flEN7UELfTm-Wg
  secure: true