spring:
  application:
    name: core
  security:
    jwt:
      secret_key: eyJhbGciOiJIUzUxMiJ9eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTcwMTA1NjM3OSwiaWF0IjoxNzAx
      expiration_time: 5
cloudiary:
  cloud_name: dm256lpnu
  api_key: 463632651578279
  api_secret: CEQdGRFAMKw29flEN7UELfTm-Wg
  secure: true